### ISSUE TITLE
 can you provide the derivation of Differentiable Homography？

### ISSUE THREAD

**Issue by Jan-jin** [YoYo000/MVSNet#15]
Thanks for your work.
I have implemented the code on DTU dataset, and the result is same with yours.
However，when I run this model on my own data，it doesn't work. I looked for why, and found that the coordinate system representation in my data is different from yours, so the extrinsic and intrinsic matrix is different.
This caused your core parts (Differentiable Homography) not to work for my own data, so I have to re-derive this formula. The introduction to differentiable homography in your paper is relatively simple for me since I am a new learner.
![formula](https://user-images.githubusercontent.com/20883762/49561551-d3bfd880-f952-11e8-8bea-2bbf3b23842e.jpg)

If it is convenient, can you provide the derivation of this formula? I don’t particularly understand what the middle part means.![formula2](https://user-images.githubusercontent.com/20883762/49561579-f9e57880-f952-11e8-8f3b-7278427018ce.jpg)
 (BTW, I use the coordinate system in photogrammetry).

Sorry to bother you and look forward to your reply.

**Comment by YoYo000** [comment]
Hi Jan-jin,

I did not derive the homography myself before. The deviation should be exactly the same as in the classical plane sweeping stereo, which I think you could find hints in the [wiki](https://en.wikipedia.org/wiki/Homography_(computer_vision)) or the book "Multiple View Geometry in Computer Vision" by Richard Hartley and Andrew Zisserman.

Yao

**Comment by hzlajojo** [comment]
@YoYo000 
Hi, Yoyo, first of all, thank you for your inspiring work.
I'm going to using your code for my project. I'd like to ask one question: could I use the equation above for the affine camera model instead of the perspective model? (Or should I derive a different homography for affine model?)
![image](https://user-images.githubusercontent.com/30767295/140670595-1540a76b-3bb6-4c91-bdd2-99d23fea629d.png)

I would be so appreciated if you can see this message and reply me.
